"use client";

import { db } from "@/lib/firebase";
import { doc, setDoc } from "firebase/firestore";

const players = [
  // Bramkarze
  {
    id: "thibaut_courtois",
    name: "Thibaut Courtois",
    position: "GK",
    rarity: "laliga",
    overall: 91,
    level: 1,
    stats: { DYN: 70, TEC: 85, INS: 88 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "belgium",
    imageUrl: "/players/courtois.png",
  },
  {
    id: "andriy_lunin",
    name: "Andriy Lunin",
    position: "GK",
    rarity: "laliga",
    overall: 76,
    level: 1,
    stats: { DYN: 65, TEC: 70, INS: 72 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "ukraine",
    imageUrl: "/players/lunin.png",
  },
  {
    id: "fran_gonzalez",
    name: "Fran González",
    position: "GK",
    rarity: "laliga",
    overall: 70,
    level: 1,
    stats: { DYN: 62, TEC: 68, INS: 70 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "spain",
    imageUrl: "/players/fran_gonzalez.png",
  },

  // Obrońcy
  {
    id: "dean_huijsen",
    name: "Dean Huijsen",
    position: "DF",
    rarity: "laliga",
    overall: 74,
    level: 1,
    stats: { DYN: 78, TEC: 65, INS: 60 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "netherlands",
    imageUrl: "/players/huijsen.png",
  },
  {
    id: "eder_militao",
    name: "Éder Militão",
    position: "DF",
    rarity: "laliga",
    overall: 84,
    level: 1,
    stats: { DYN: 82, TEC: 75, INS: 78 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "brazil",
    imageUrl: "/players/militao.png",
  },
  {
    id: "raul_asencio",
    name: "Raúl Asencio",
    position: "DF",
    rarity: "laliga",
    overall: 70,
    level: 1,
    stats: { DYN: 72, TEC: 60, INS: 58 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "spain",
    imageUrl: "/players/asencio.png",
  },
  {
    id: "antonio_rudiger",
    name: "Antonio Rüdiger",
    position: "DF",
    rarity: "laliga",
    overall: 85,
    level: 1,
    stats: { DYN: 84, TEC: 73, INS: 80 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "germany",
    imageUrl: "/players/rudiger.png",
  },
  {
    id: "david_alaba",
    name: "David Alaba",
    position: "DF",
    rarity: "laliga",
    overall: 87,
    level: 1,
    stats: { DYN: 82, TEC: 85, INS: 80 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "austria",
    imageUrl: "/players/alaba.png",
  },
  {
    id: "ferland_mendy",
    name: "Ferland Mendy",
    position: "DF",
    rarity: "laliga",
    overall: 82,
    level: 1,
    stats: { DYN: 83, TEC: 74, INS: 72 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "france",
    imageUrl: "/players/mendy.png",
  },
  {
    id: "fran_garcia",
    name: "Fran García",
    position: "DF",
    rarity: "laliga",
    overall: 75,
    level: 1,
    stats: { DYN: 79, TEC: 68, INS: 65 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "spain",
    imageUrl: "/players/fran_garcia.png",
  },
  {
    id: "trent_alexander-arnold",
    name: "Trent Alexander-Arnold",
    position: "DF",
    rarity: "laliga",
    overall: 88,
    level: 1,
    stats: { DYN: 86, TEC: 90, INS: 85 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "england",
    imageUrl: "/players/trent_arnold.png",
  },
  {
    id: "daniel_carvajal",
    name: "Daniel Carvajal",
    position: "DF",
    rarity: "laliga",
    overall: 83,
    level: 1,
    stats: { DYN: 81, TEC: 77, INS: 73 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "spain",
    imageUrl: "/players/carvajal.png",
  },

  // Pomocnicy
  {
    id: "aurelien_tchouameni",
    name: "Aurélien Tchouaméni",
    position: "MF",
    rarity: "laliga",
    overall: 86,
    level: 1,
    stats: { DYN: 84, TEC: 83, INS: 79 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "france",
    imageUrl: "/players/tchouameni.png",
  },
  {
    id: "federico_valverde",
    name: "Federico Valverde",
    position: "MF",
    rarity: "laliga",
    overall: 87,
    level: 1,
    stats: { DYN: 88, TEC: 82, INS: 85 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "uruguay",
    imageUrl: "/players/valverde.png",
  },
  {
    id: "eduardo_camavinga",
    name: "Eduardo Camavinga",
    position: "MF",
    rarity: "laliga",
    overall: 83,
    level: 1,
    stats: { DYN: 85, TEC: 80, INS: 78 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "france",
    imageUrl: "/players/camavinga.png",
  },
  {
    id: "dani_ceballos",
    name: "Dani Ceballos",
    position: "MF",
    rarity: "laliga",
    overall: 78,
    level: 1,
    stats: { DYN: 80, TEC: 78, INS: 75 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "spain",
    imageUrl: "/players/ceballos.png",
  },
  {
    id: "jude_bellingham",
    name: "Jude Bellingham",
    position: "MF",
    rarity: "laliga",
    overall: 88,
    level: 1,
    stats: { DYN: 90, TEC: 85, INS: 87 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "england",
    imageUrl: "/players/bellingham.png",
  },
  {
    id: "reinier",
    name: "Reinier",
    position: "MF",
    rarity: "laliga",
    overall: 74,
    level: 1,
    stats: { DYN: 75, TEC: 70, INS: 72 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "brazil",
    imageUrl: "/players/reinier.png",
  },

  // Napastnicy
  {
    id: "vinicius_junior",
    name: "Vinicius Junior",
    position: "FW",
    rarity: "laliga",
    overall: 89,
    level: 1,
    stats: { DYN: 94, TEC: 88, INS: 85 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "brazil",
    imageUrl: "/players/vinicius.png",
  },
  {
    id: "rodrygo",
    name: "Rodrygo",
    position: "FW",
    rarity: "laliga",
    overall: 85,
    level: 1,
    stats: { DYN: 90, TEC: 84, INS: 80 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "brazil",
    imageUrl: "/players/rodrygo.png",
  },
  {
    id: "arda_guler",
    name: "Arda Güler",
    position: "FW",
    rarity: "laliga",
    overall: 78,
    level: 1,
    stats: { DYN: 80, TEC: 77, INS: 75 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "turkey",
    imageUrl: "/players/guler.png",
  },
  {
    id: "brahim_diaz",
    name: "Brahim Díaz",
    position: "FW",
    rarity: "laliga",
    overall: 82,
    level: 1,
    stats: { DYN: 85, TEC: 80, INS: 78 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "spain",
    imageUrl: "/players/diaz.png",
  },
  {
    id: "kylian_mbappe",
    name: "Kylian Mbappé",
    position: "FW",
    rarity: "laliga",
    overall: 92,
    level: 1,
    stats: { DYN: 93, TEC: 91, INS: 88 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "france",
    imageUrl: "/players/mbappe.png",
  },
  {
    id: "endrick",
    name: "Endrick",
    position: "FW",
    rarity: "laliga",
    overall: 76,
    level: 1,
    stats: { DYN: 85, TEC: 75, INS: 70 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "brazil",
    imageUrl: "/players/endrick.png",
  },
  {
    id: "alvaro_rodriguez",
    name: "Álvaro Rodríguez",
    position: "FW",
    rarity: "laliga",
    overall: 77,
    level: 1,
    stats: { DYN: 78, TEC: 74, INS: 72 },
    clubId: "realmadrid",
    leagueId: "laLiga",
    nationId: "spain",
    imageUrl: "/players/alvaro_rodriguez.png",
  },
];

export default function AddRealMadridPlayersButton() {
  const handleAddPlayers = async () => {
    try {
      for (const player of players) {
        await setDoc(doc(db, "cards", player.id), player);
      }
      alert("Dodano wszystkich piłkarzy Realu Madryt do bazy!");
    } catch (err) {
      console.error("Błąd przy dodawaniu kart:", err);
      alert("Coś poszło nie tak przy dodawaniu kart.");
    }
  };

  return (
    <button
      onClick={handleAddPlayers}
      className="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded"
    >
      Dodaj piłkarzy Realu Madryt (wszyscy)
    </button>
  );
}
